const MIN_GROUP_WORDS = 0;
const MIN_PAGE_WORDS = 0;
const MAX_GROUP_WORDS = 7;
const MAX_PAGE_WORDS = 30;
const MAX_LIMIT_WORDS = 3600;

export { MIN_GROUP_WORDS, MIN_PAGE_WORDS, MAX_GROUP_WORDS, MAX_PAGE_WORDS, MAX_LIMIT_WORDS };
