const MIN_GROUP_WORDS = 0;
const MIN_PAGE_WORDS = 0;
const MAX_GROUP_WORDS = 6;
const MAX_PAGE_WORDS = 29;
const MAX_LIMIT_WORDS = 3600;
const MIN_LIMIT_WORDS = 20;

export { MIN_GROUP_WORDS, MIN_PAGE_WORDS, MAX_GROUP_WORDS, MAX_PAGE_WORDS, MAX_LIMIT_WORDS, MIN_LIMIT_WORDS };
