const FULL_DASHARRAY = 283;
const WARNING_TIME = 30;
const ALERT_TIME = 15;
const TIME_LIMIT = 60;
const TIME_INTERVAL = 1000;

export { FULL_DASHARRAY, WARNING_TIME, ALERT_TIME, TIME_LIMIT, TIME_INTERVAL };
